export const RING_ON_NEUTRAL_MOBILE_GOAL_HIGH_BRANCH_PT = 10;
export const RING_ON_ANY_OTHER_MOBILE_GOAL_BRANCH_PT = 3;
export const RING_ON_MOBILE_GOAL_BASE_PT = 1;
export const MOBILE_GOAL_IN_ALLIANCE_HOME_ZONE_PT = 20;
export const ROBOT_ELEVATED_PT = 30;
export const MOBILE_GOAL_ELEVATED_PT = 40;